# .rubocop.yml
---
inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

AllCops:
  NewCops: enable

Style/PercentLiteralDelimiters:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/TernaryParentheses:
  Enabled: false

Style/RedundantParentheses:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Metrics/MethodLength:
  Max: 20

Style/HashSyntax:
  EnforcedShorthandSyntax: never

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

Gemspec/RequiredRubyVersion:
  Enabled: false
